#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = "Alexander Stewart"


class ProgDefaults:
    ENTREZ_EMAIL = ""
    ENTREZ_API = ""

    ORDER_DICT = {"species": 0, "accession": 1, "range": 2, "gene": 3, "date": 4, "length": 5}
    OUTDIR_PREFIX = "scraped_sequences"
    COMB_FILE = "all_chunks"
    CHUNK_SIZE = 2000
    EXCLUDE_TERMS = ["unisexual", "cf.", " x "]
    FOCAL_SEQFILE_NAME = "focal_scraped_sequences.fasta"
    SPP_FILE_NAME = "captured_caudate_taxa"

    # outfmt type caster #
    BLASTN_DEFAULT_OUTFMT_SIX = {0: "qseqid", 1: "sseqid", 2: "pident", 3: "length", 4: "mismatch", 5: "gapopen",
                                 6: "qstart", 7: "qend", 8: "sstart", 9: "send", 10: "evalue", 11: "bitscore"}
    BLASTN_TYPES = dict(qseqid=str, qgi=str, qacc=str, qaccver=str, qlen=int, sseqid=str, sallseqid=str, sgi=str,
                        sallgi=str, sacc=str, saccver=str, sallacc=str, slen=int, qstart=int, qend=int,
                        sstart=int, send=int, qseq=str, sseq=str, evalue=float, bitscore=float, score=int,
                        length=int, pident=float, nident=int, mismatch=int, positive=int, gapopen=int, gaps=int,
                        ppos=float, frames=str, qframe=str, sframe=str, btop=str, staxids=str, sscinames=str,
                        scomnames=str, sblastnames=str, sskingdoms=str, stitle=str, salltitles=str, sstrand=str,
                        qcovs=int, qcovhsp=int)
    GTF_FORMAT = {"seqname": 0, "source": 1, "feature": 2, "start": 3, "end": 4, "score": 5, "strand": 6,
                  "frame": 7, "attribute": 8}

    MITO_GOIS = {"nadh dehydrogenase subunit 4": "nd4",
                 "nadh dehydrogenase subunit iv": "nd4",
                 "nd4": "nd4",

                 "nadh dehydrogenase subunit 2": "nd2",
                 "nadh dehydrogenase subunit ii": "nd2",
                 "nd2": "nd2",

                 "cytochrome c oxidase subunit 1": "cox1",
                 "cytochrome c oxidase subunit i": "cox1",
                 "cytochrome oxidase subunit 1": "cox1",
                 "cytochrome oxidase subunit i": "cox1",
                 "chytochrome c oxidase subunit 1": "cox1",
                 "chytochrome c oxidase subunit i": "cox1",
                 "cox1": "cox1",
                 "co1": "cox1",

                 "cytochrome c oxidase subunit 2": "cox2",
                 "cytochrome c oxidase subunit ii": "cox2",
                 "cytochrome oxidase subunit 2": "cox2",
                 "cytochrome oxidase subunit ii": "cox2",
                 "chytochrome c oxidase subunit 2": "cox2",
                 "chytochrome c oxidase subunit ii": "cox2",
                 "cox2": "cox2",
                 "co2": "cox2",

                 "12s ribosomal rna": "12s",
                 "s-rrna": "12s",
                 "small subunit ribosomal rna": "12s",
                 "12s small subunit ribosomal rna": "12s",
                 "12s": "12s",

                 "16s ribosomal rna": "16s",
                 "16s ribosoaml rna": "16s",
                 "l-rrna": "16s",
                 "large subunit ribosomal rna": "16s",
                 "16s large subunit ribosomal rna": "16s",
                 "16s": "16s",

                 "cytochrome b": "cytb",
                 "cytochrome b apoenzyme": "cytb",
                 "cytb": "cytb",

                 "brain derived neurotrophic factor": "bdnf",
                 "brain-derived neurotrophic factor": "bdnf",
                 "bdnf": "bdnf",

                 "rag1": "rag1",
                 "recombinase activating protein": "rag1",
                 "recombinase activating protein 1": "rag1",
                 "recombination activating gene 1": "rag1",
                 "recombination activating protein 1": "rag1",
                 "recombination activating protein-1": "rag1",
                 "recombination activation protein 1": "rag1",
                 "v(d)j recombinase subunit": "rag1",

                 "pro-opimelanocortin": "pomc",
                 "pro-opiomelanocortin": "pomc",
                 "proopiomelanocortin": "pomc",
                 "pomc": "pomc",

                 "solute carrier family 8 member 3": "slc8a3",
                 "slc8a3": "slc8a3"}

    ROVITO_SHEN_GOIS = {'bptf': 'bptf',
                        'bromodomain phd finger transcription factor': 'bptf',

                        'dolk': 'dolk',
                        'dolichol kinase': 'dolk',

                        'fat-4': 'fat4',
                        'fat4': 'fat4',
                        'fat tumor suppressor-like protein 4': 'fat4',
                        'fat atypical cadherin 4': 'fat4',
                        'protocadherin fat 4': 'fat4',
                        "fatj": 'fat4',

                        'kiaa1239': 'kiaa1239',
                        'kiaa1239 protein': 'kiaa1239',
                        'truncated kiaa1239 protein': 'kiaa1239',
                        'kiaa1239-like protein': 'kiaa1239',
                        'nwd2': 'kiaa1239',

                        'kiaa2013': 'kiaa2013',
                        'kiaa2013-like protein': 'kiaa2013',


                        'panx2': 'panx2',
                        'panx-2': 'panx2',
                        'pannexin 2': 'panx2',

                        'ppl': 'ppl',
                        'periplakin': 'ppl',

                        'pdp1': 'pdp1',
                        'pdp-1': 'pdp1',
                        'pyruvate dehyrogenase phosphatase catalytic subunit 1': 'pdp1',

                        'rag2': 'rag2',
                        'rag-2': 'rag2',
                        'recombination activating protein 2': 'rag2',

                        'sacs': 'sacs',
                        'sacsin': 'sacs',
                        'spastic ataxia of charlevoix-saguenay': 'sacs',
                        'spastic ataxia of charlevoix-saguenay (sacsin)': 'sacs',

                        'ttn': 'ttn',
                        'titin': 'ttn',

                        'adnp': 'adnp',
                        'activity-dependent neuroprotector homeobox': 'adnp',

                        'ankrd50': 'ankrd50',
                        'ankyrin repeat domain 50': 'ankrd50',
                        'ankyrin repeat domain protein 50': 'ankrd50',

                        'cand-1': 'cand1',
                        'cand1': 'cand1',
                        'cullin-associated and neddylation-dissociated 1': 'cand1',
                        'cullin-associated nedd8-dissociated protein 1': 'cand1',

                        'cpt2': 'cpt2',
                        'carnitine palmitoyltransferase 2': 'cpt2',

                        'dbc1': 'dbc1',
                        'deleted in bladder cancer 1': 'dbc1',
                        'bone morphogenetic protein/retinoic acid inducible neural-specific 1': 'dbc1',
                        'brinp1': 'dbc1',

                        'det-1': 'det1',
                        'det1': 'det1',
                        'de-etiolated-like protein 1': 'det1',

                        'disp-1': 'disp1',
                        'disp1': 'disp1',
                        'dispatched-like protein 1': 'disp1',

                        'disp2': 'disp2',
                        'disp-2': 'disp2',
                        'dispatched homolog 2': 'disp2',
                        'dispatched-like protein 2': 'disp2',

                        'dnah3': 'dnah3',
                        'dnah-3': 'dnah3',
                        'dynein axonemal heavy chain 3': 'dnah3',
                        'axonemal dynein heavy chain 3': 'dnah3',
                        'dynein, axonemal, heavy chain 3': 'dnah3',

                        'dsel': 'dsel',
                        'dermatan sulfate epimerase-like protein': 'dsel',

                        'enc1': 'enc1',
                        'enc-1': 'enc1',
                        'ectodermal-neural cortex 1': 'enc1',
                        'ectodermal-neural cortex 1 (with btb domain)': 'enc1',

                        'extl-3': 'extl3',
                        'extl3': 'extl3',
                        'exostoses multiple-like 3 protein': 'extl3',
                        'exostosin-like glycosyltransferase 3': 'extl3',

                        'fat1': 'fat1',
                        'fat atypical cadherin 1': 'fat1',

                        'fat2': 'fat2',
                        'fat atypical cadherin 2': 'fat2',

                        'fem1b': 'fem1b',
                        'fem-1 homolog b': 'fem1b',
                        'fem-1-like protein b': 'fem1b',

                        'ficd': 'ficd',
                        'fic domain containing': 'ficd',
                        'fic domain-containing protein': 'ficd',

                        'flrt3': 'flrt3',
                        'fibronectin leucine rich transmembrane protein 3': 'flrt3',

                        'frem2': 'frem2',
                        'fras1 related extracellular matrix protein 2': 'frem2',

                        'fut9': 'fut9',
                        'fucosyltransferase 9 alpha': 'fut9',
                        'fucosyltransferase 9 (alpha (1,3) fucosyltransferase)': 'fut9',

                        'fzd4': 'fzd4',
                        'frizzled family receptor 4': 'fzd4',

                        'grm-2': 'grm2',
                        'glutamate receptor metabotropic 2': 'grm2',
                        'grm2': 'grm2',
                        'glutamate metabotropic receptor 2': 'grm2',
                        'glutamate receptor, metabotropic 2': 'grm2',

                        'kcnf1': 'kcnf1',
                        'kcnf-1': 'kcnf1',
                        'potassium voltage-gated channel subfamily f member 1': 'kcnf1',
                        'potassium voltage-gated channel, subfamily f member 1': 'kcnf1',
                        'potassium voltage-gated channel, subfamily f, member 1': 'kcnf1',
                        'potassium voltage-gated channel modifier subfamily f member 1': 'kcnf1',

                        'lig4': 'lig4',
                        'lig-4': 'lig4',
                        'ligase iv': 'lig4',
                        'atp-dependent ligase iv': 'lig4',
                        'ligase iv, dna, atp-dependent': 'lig4',
                        'atp-dependent dna ligase iv': 'lig4',

                        'lingo1': 'lingo1',
                        'leucine rich repeat and ig domain containing 1': 'lingo1',

                        'lingo2': 'lingo2',
                        'leucine rich repeat and ig domain containing 2': 'lingo2',

                        'lphn2': 'lphn2',
                        'lphn-2': 'lphn2',
                        'latrophilin 2': 'lphn2',
                        'adgrl2': 'lphn2',

                        'lrrn1': 'lrrn1',
                        'lrrn-1': 'lrrn1',
                        'leucine rich repeat neuronal 1': 'lrrn1',
                        'leucine-rich repeat neuronal protein 1': 'lrrn1',

                        'lrrtm4': 'lrrtm4',
                        'leucine rich repeat transmembrane neuronal 4': 'lrrtm4',

                        'mb21d2': 'mb21d2',
                        'mab-21 domain containing 2': 'mb21d2',

                        'mgat4c': 'mgat4c',
                        'mannosyl alpha-1,3--glycoprotein beta-1,4-n-acetylglucosaminyltransferase isozyme c': 'mgat4c',
                        'putative mannosyl (alpha-1,3-)-glycoprotein beta-1,4-n-acetylglucosaminyltransferase, isozyme c (putative)': 'mgat4c',

                        'mios': 'mios',
                        'missing oocyte meiosis regulator': 'mios',
                        'missing oocyte, meiosis regulator, homolog': 'mios',
                        'missing oocyte meiosis regulator-like protein': 'mios',

                        'nhs': 'nhs',
                        'nance-horan syndrome protein': 'nhs',
                        'nance-horan syndrome (congenital cataracts and dental anomalies)': 'nhs',

                        'pclo': 'pclo',
                        'piccolo presynaptic cytomatrix protein': 'pclo',

                        'pik3cg': 'pik3cg',
                        'phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit gamma': 'pik3cg',
                        'phosphatidylinositol-4,5-bisphosphate 3-kinase, catalytic subunit gamma': 'pik3cg',

                        'poz': 'poz',
                        'kelch repeat and btb domain-containing protein 2': 'poz',
                        'kelch repeat and btb domain-containing 2 protein': 'poz',
                        'kbtbd2': 'poz',
                        'kelch repeat and btb (poz) domain containing 2': 'poz',

                        'ror2': 'ror2',
                        'receptor tyrosine kinase-like orphan receptor 2': 'ror2',

                        'sall1': 'sall1',
                        'sal-like 1': 'sall1',
                        'sal-like protein 1': 'sall1',

                        'sh3bp4': 'sh3bp4',
                        'sh3-domain binding protein 4': 'sh3bp4',

                        'slitrk1': 'slitrk1',
                        'slit and ntrk-like family, member 1': 'slitrk1',
                        'slit and ntrk-like protein 1-like protein': 'slitrk1',

                        'socs5': 'socs5',
                        'suppressor of cytokine signaling 5': 'socs5',

                        'ston2': 'ston2',
                        'stonin 2': 'ston2',

                        'svep1': 'svep1',
                        'sushi, von willebrand factor type a, egf and pentraxin domain containing 1': 'svep1',
                        'sushi, von willebrand factor type a, egf and pentraxin domain containing protein 1': 'svep1',
                        'sushi, von willebrand factor type a, egf and pentraxin domain-containing protein 1': 'svep1',

                        'zbed-4': 'zbed4',
                        'zbed4': 'zbed4',
                        'zinc finger bed-type containing 4 protein': 'zbed4',
                        'bed-type zinc finger-containing 4 protein': 'zbed4',
                        'zinc finger bed-type containing protein 4': 'zbed4',

                        'zhx2': 'zhx2',
                        'zinc fingers and homeoboxes 2': 'zhx2'}

    MITO_GOIS.update(ROVITO_SHEN_GOIS)

    HIME_TO_SYMBOL = {
        1: "prdm16",
        4: "kif1b",
        5: "spen",
        10: "mast2",
        11: "jun",
        13: "adgrl2",
        14: "znf644",
        15: "plppr4",
        16: "s1pr1",
        17: "celsr1",
        20: "rbm15",
        28: "kcnd3",
        30: "olfml3",
        31: "bcl9",
        34: "rasal2",
        35: "angptl1",
        36: "b3galt2",
        38: "lgr5",
        41: "disp1",
        45: "sipa1l1",
        46: "kif26b",
        47: "pxdn",
        48: "kcnf1",
        49: "kcns3",
        53: "birc6",
        54: "msh6",
        55: "ston1",
        56: "gpr75",
        57: "ccdc85a",
        59: "bcl11a",
        61: "lrrtm1",
        62: "rnf103",
        63: "ranbp2",
        65: "zeb2",
        69: "ttn",
        78: "bmpr2",
        80: "klf7",
        82: "znf142",
        86: "iqsec1",
        88: "wnt7a",
        92: "klhl40",
        93: "snrk",
        95: "bsn",
        97: "pdzrn3",
        99: "ccdc80",
        100: "usf3",
        102: "znf148",
        105: "kbtbd12",
        107: "siah2",
        109: "gpr87",
        110: "igsf10",
        112: "skil",
        113: "ghsr",
        115: "kiaa0232",
        116: "nwd2",
        118: "shroom3",
        121: "ndnf",
        122: "ankrd50",
        123: "fat4",
        124: "fatj",
        125: "fat4",
        126: "pcdh18",
        127: "nr3c2",
        130: "sorbs2",
        132: "fat1",
        135: "gcnt4",
        136: "apc",
        137: "sema6a",
        138: "dmxl1",
        141: "adrb2",
        144: "slc26a2",
        146: "arsi",
        147: "fat2",
        149: "tenm2",
        151: "rreb1",
        152: "dsp",
        153: "hivep1",
        154: "atxn1",
        155: "bicral",
        156: "klhl31",
        159: "htr1e",
        160: "znf292",
        161: "sim1",
        162: "bend3",
        163: "ctgf",
        164: "nhsl1",
        165: "hivep2",
        166: "mibp1",
        169: "grm1",
        172: "akap12",
        173: "syne1",
        174: "arid1b",
        175: "dll1",
        177: "sp4",
        179: "pclo",
        182: "cttnbp2",
        183: "plxna4",
        184: "nf-m",
        187: "npbwr1",
        191: "fam110b",
        192: "chd7",
        193: "ythdf3",
        194: "vcpip1",
        196: "zfhx4",
        197: "pdp1",
        198: "zfpm2",
        199: "zhx2",
        200: "klhl38",
        201: "rnf139",
        202: "kank1",
        203: "dmrt3",
        204: "kcnv2",
        208: "trpm3",
        209: "dapk1",
        210: "nfil3",
        211: "ror2",
        212: "grin3a",
        214: "svep1",
        216: "zbtb34",
        217: "camsap1",
        218: "adarb2",
        219: "fam171a1",
        220: "kiaa1217",
        222: "zeb1",
        224: "slc18a3",
        225: "ank3",
        226: "arid5b",
        227: "jmjd1c",
        229: "ndst1",
        230: "kat6b",
        231: "moz",
        234: "sh3pxd2a",
        239: "rag1",
        240: "prdm11",
        241: "chst1",
        242: "kbtbd4",
        243: "dagla",
        244: "cortbp1",
        245: "shank2",
        246: "tenm4",
        248: "prss23",
        249: "fzd4",
        251: "grm5",
        252: "fat3",
        253: "amotl1",
        254: "maml2",
        255: "zc3h12c",
        258: "kmt2a",
        262: "igsf9b",
        264: "bicd1",
        265: "abcd2",
        267: "pdzrn4",
        268: "cand1",
        269: "dyrk2",
        271: "uhrf1bp1l",
        272: "nuak1",
        274: "ccdc92",
        275: "tmem132d",
        278: "sacs",
        279: "sacs",
        280: "gpr12",
        281: "stard13",
        282: "frem3",
        284: "akap11",
        285: "pcdh17",
        287: "klf5",
        288: "mycbp2",
        290: "nova1",
        291: "npas3",
        293: "socs5",
        294: "slc8a3",
        296: "ston2",
        297: "gpr68",
        299: "begain",
        304: "disp2",
        305: "rhov",
        306: "vps18",
        307: "vps18",
        309: "ttbk2",
        310: "map1a",
        311: "sema6d",
        312: "dmxl2",
        317: "bnc1",
        320: "dnah3",
        321: "znf423",
        324: "nfatc3",
        325: "zfhx3",
        327: "rai1",
        328: "smcr8",
        329: "med1",
        331: "klhl11",
        334: "tex2",
        335: "kcnj2",
        336: "cdc42ep4",
        337: "btbd17",
        339: "tnrc6c",
        340: "pycr1",
        343: "znf521",
        345: "chst8",
        346: "asxl3",
        347: "setbp1",
        348: "dsel",
        349: "tshz1",
        350: "sall3",
        353: "znf536",
        354: "znf536",
        355: "tshz3",
        358: "flrt3",
        359: "rin2",
        360: "ncoa6",
        362: "tshz2",
        367: "tiam1",
        368: "dop1b",
        369: "kcnj15",
        371: "zbtb21",
        372: "mical3",
        375: "elfn2",
        376: "nhs",
        378: "bcor",
        379: "nexmif",
    }
